language: node_js
node_js:
  - 0.10
  - 0.9
  - 0.8

secure: "E85RwCYAXs8cYPmQIO1DyHQTIHe5L89/ffvOF6795ClATpz9SWBNb2OcYHT259LMD6rnyLTrFkwZzepj8gXNsKYNAiZpLoumv41s6npkL0Pu8DTRHKl6WM1i0cG71hEaK9hyt20Yn/ogPtYybHe1S9j6mc2+DY3x2jxK8cmJDH0="
